import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy-initialize Gemini client to avoid crashing on startup if API key is not yet set
let aiClient: GoogleGenAI | null = null;
function getAI(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required. Please configure it in Settings > Secrets.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

// Endpoint to generate structured slides using Gemini 3.5-flash
app.post("/api/generate-slides", async (req, res) => {
  try {
    const { text } = req.body;
    if (!text || typeof text !== "string" || !text.trim()) {
      return res.status(400).json({ error: "Input text is required" });
    }

    const ai = getAI();
    
    const responseSchema = {
      type: Type.OBJECT,
      properties: {
        slides: {
          type: Type.ARRAY,
          description: "An array of structured slides generated from the text.",
          items: {
            type: Type.OBJECT,
            properties: {
              title: {
                type: Type.STRING,
                description: "A short, punchy slide title. Keep it under 8 words."
              },
              body: {
                type: Type.STRING,
                description: "The core content of the slide. Use a few concise, structured bullet points or paragraphs. Keep it visual, punchy, and clear."
              }
            },
            required: ["title", "body"]
          }
        }
      },
      required: ["slides"]
    };

    const prompt = `Analyze the following research material, documents, or raw notes.
Structure it into an elegant, high-impact presentation slide deck.
Separate the concepts logically so that each slide contains one clear central idea with a punchy title and concise, highly readable body content (e.g., structured bullet points or short, descriptive paragraphs).
Do not combine too many topics into a single slide. Aim for a balanced deck of about 3 to 8 slides depending on the input length.

Research material/Notes:
${text}`;

    const aiResponse = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        systemInstruction: "You are an elite presentation designer and visual content strategist. You excel at distilling complex text and notes into beautifully organized, visual, and highly impact slides."
      }
    });

    const responseText = aiResponse.text;
    if (!responseText) {
      throw new Error("No response content generated by the AI model");
    }

    const parsedData = JSON.parse(responseText);
    res.json(parsedData);
  } catch (error: any) {
    console.error("Error generating slides:", error);
    res.status(500).json({ 
      error: error.message || "Failed to generate slides with Google AI." 
    });
  }
});

// Endpoint for ChatGPT-like continuous chat with no limits
app.post("/api/chat", async (req, res) => {
  try {
    const { messages } = req.body;
    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: "Messages array is required" });
    }

    const ai = getAI();
    
    // Map client messages to Gemini's format: { role: 'user' | 'model', parts: [{ text: string }] }
    const contents = messages.map((m: any) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }]
    }));

    const aiResponse = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: contents,
      config: {
        systemInstruction: "You are AuraGPT, an elite, highly creative conversational AI assistant powered by Google Gemini, built directly into AuraSlide Studio. You provide limitless assistance with same capabilities as ChatGPT. You are highly intelligent, articulate, and friendly. Help the user with brainstorming, researching, planning presentations, writing code, or general conversation. You can format answers beautifully with paragraphs, clean bullet points, or lists."
      }
    });

    res.json({ content: aiResponse.text || "" });
  } catch (error: any) {
    console.error("Error in chat endpoint:", error);
    res.status(500).json({ 
      error: error.message || "Failed to generate chat response with Google AI." 
    });
  }
});

// Vite middleware integration
async function setupVite() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

setupVite();
